Added the ability to upload files
BrightLocal/BrightLocal-API-Helper pull request #8
Opened 2017-01-10 14:02 UTC by itch

need for the task https://brightlocal.atlassian.net/browse/API-28

2017-01-11 10:42 UTC, tenmozes approved these changes

2017-01-11 11:00 UTC, ejeliot requested changes

2017-01-11 11:00 UTC, ejeliot commented on src/BrightLocal/Api.php
> +    private function get_options(string $httpMethod, array $params):array {
Please don't use PHP 7 syntax in the wrapper. We should use PHP 5.6 compatible code.

2017-01-11 11:15 UTC, ejeliot approved these changes

2017-08-11 11:26 UTC, ejeliot approved these changes

2017-08-11 11:26 UTC, merged